version: "2"

services:
  polymorph_server:
    build: .
    command: node src/server.js
    ports:
      - 8080:8080
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
